//
//  DetectionClassesTests.swift
//  DogtectorTests
//
//  Created by Bartłomiej Pluta
//

import XCTest
import Combine
@testable import Dogtector

class DetectionClassesTests: XCTestCase {
    var sut: [DetectionClassInfo]!
    private var cancellable: AnyCancellable?
    
    override func setUp() {
        let manager = PlistDataRepository(appState: Store<AppState>(AppState()))
        let expectation = expectation(description: "\(#function) at \(#line)")
        cancellable = manager.loadClassDetectionData()
            .sink(receiveCompletion: { _ in
                expectation.fulfill()
            }, receiveValue: { [weak self] values in
                self?.sut = values
            })
        waitForExpectations(timeout: 2, handler: nil)
    }

    override func tearDown() {
        sut = nil
        cancellable?.cancel()
        cancellable = nil
    }

    func testPlistDecoder() {
        XCTAssert(sut != nil)
    }

    func testClassAmount() {
        XCTAssert(expectedClasses.count == sut.count)
    }

    func testObjectOrder() {
        XCTAssert(expectedClasses.count == sut.count)
        for (index, (classObject, currentClass)) in zip(sut, expectedClasses).enumerated() {
            XCTAssert(
                classObject.identifier == currentClass,
                "Wrong index - at \(index) index theres should be \(currentClass) instead of \(classObject.identifier)"
            )
        }
    }

    func testIfAllObjectsContainName() {
        for (index, classObject) in sut.enumerated() {
            XCTAssertFalse(
                classObject.primaryName.isEmpty,
                "Object at index \(index) (\(classObject.identifier)) does not contain primary name"
            )
        }
    }

    func testIfAllObjectsContainLicenceInfo() {
        for (index, classObject) in sut.enumerated() {
            XCTAssertFalse(
                classObject.licenceInfo?.isEmpty ?? true,
                "Object at index \(index) (\(classObject.identifier)) does not contain licence info"
            )
        }
    }

    func testIfAllObjectsContainImage() {
        for (index, classObject) in sut.enumerated() {
            XCTAssert(
                classObject.image != nil,
                "Object at index \(index) (\(classObject.identifier)) does not contain full sized image"
            )
        }
    }

    func testIfAllObjectsContainMiniatureImage() {
        for (index, classObject) in sut.enumerated() {
            XCTAssert(
                classObject.miniatureImage != nil,
                "Object at index \(index) (\(classObject.identifier)) does not contain miniature image"
            )
        }
    }
    
    func testIfAllObjectsContainOriginData() {
        for (index, classObject) in sut.enumerated() {
            XCTAssertFalse(
                classObject.originCountries.isEmpty,
                "Object at index \(index) (\(classObject.identifier)) does not contain origin data"
            )
        }
    }
}

extension DetectionClassesTests {
    var expectedClasses: [String] {[
        "affenpinscher",
        "afghanhound",
        "afghanshepherd",
        "aidi",
        "airedaleterrier",
        "akbash",
        "akitainu",
        "alanoespanol",
        "alaskankleekai",
        "alaskanmalamute",
        "alpinedachsbracke",
        "americanakita",
        "americanbulldog",
        "americancockerspaniel",
        "americanenglishcoonhound",
        "americaneskimodog",
        "americanfoxhound",
        "americanhairlessterrier",
        "americanpitbullterrier",
        "americanstaffordshireterrier",
        "americanwaterspaniel",
        "anatolianshepherd",
        "andalusianhound",
        "anglofrancaisdepetitevenerie",
        "appenzellersennenhund",
        "ariegeois",
        "armeniangamprdog",
        "artoishound",
        "australiancattledog",
        "australiankelpie",
        "australianshepherd",
        "australiansilkyterrier",
        "australianstumpytailcattledog",
        "australianterrier",
        "austrianblackandtanhound",
        "austrianpinscher",
        "azawakh",
        "barakhound",
        "barbet",
        "basenji",
        "basqueshepherddog",
        "bassetartesiennormand",
        "bassetbleudegascogne",
        "bassetfauvedebretagne",
        "bassetgriffonvendeen",
        "bassethound",
        "bavarianmountainhound",
        "beagle",
        "beagleharrier",
        "beardedcollie",
        "beauceron",
        "bedlingtonterrier",
        "bergamascosheepdog",
        "bergerpicard",
        "bernerlaufhund",
        "bernesemountaindog",
        "bhotiadog",
        "bichonfrise",
        "blackandtancoonhound",
        "blackmouthcur",
        "blacknorwegianelkhound",
        "blackrussianterrier",
        "bleudegascogne",
        "bloodhound",
        "bluelacy",
        "bluepicardyspaniel",
        "bluetickcoonhound",
        "boerboel",
        "bohemianshepherd",
        "bolognese",
        "bordercollie",
        "borderterrier",
        "borzoi",
        "bostonterrier",
        "bouvierdesardennes",
        "bouvierdesflandres",
        "boxer",
        "boykinspaniel",
        "braccoitaliano",
        "braquedauvergne",
        "braquedubourbonnais",
        "braquefrancais",
        "braquesaintgermain",
        "braziliandogo",
        "brazilianterrier",
        "briard",
        "briquetgriffonvendeen",
        "brittanyspaniel",
        "broholmer",
        "brunojurahound",
        "bucovinashepherddog",
        "bulldog",
        "bullmastiff",
        "bullterrier",
        "bullykutta",
        "burgospointer",
        "cadebou",
        "cairnterrier",
        "canaandog",
        "canadianeskimodog",
        "canecorso",
        "caodecastrolaboreiro",
        "caofiladesaomiguel",
        "cardiganwelshcorgi",
        "carolinadog",
        "carpathianshepherddog",
        "catahoulaleoparddog",
        "catalansheepdog",
        "caucasianshepherddog",
        "cavalierkingcharlesspaniel",
        "centralasianshepherddog",
        "ceskyfousek",
        "ceskyterrier",
        "chesapeakebayretriever",
        "chihuahua",
        "chileanterrier",
        "chinesecresteddog",
        "chinook",
        "chippiparai",
        "chowchow",
        "clumberspaniel",
        "colombianfinohound",
        "combai",
        "cotondetulear",
        "cretanhound",
        "croatiansheepdog",
        "curlycoatedretriever",
        "cursinu",
        "czechoslovakwolfdog",
        "dachshund",
        "dalmatian",
        "dandiedinmontterrier",
        "danishswedishfarmdog",
        "doberman",
        "dogoargentino",
        "dogoguatemalteco",
        "doguedebordeaux",
        "drentsepatrijshond",
        "drever",
        "dunker",
        "dutchshepherddog",
        "dutchsmoushond",
        "easteuropeanshepherd",
        "eastsiberianlaika",
        "englishcockerspaniel",
        "englishfoxhound",
        "englishmastiff",
        "englishpointer",
        "englishsetter",
        "englishshepherd",
        "englishspringerspaniel",
        "entlebuchermountaindog",
        "estonianhound",
        "estrelamountaindog",
        "eurasier",
        "fieldspaniel",
        "filabrasileiro",
        "finnishhound",
        "finnishlapphund",
        "finnishspitz",
        "flatcoatedretriever",
        "formosanmountaindog",
        "frenchbulldog",
        "frenchspaniel",
        "galgoespanol",
        "gasconsaintongeois",
        "georgianshepherd",
        "germanhound",
        "germanlonghairedpointer",
        "germanpinscher",
        "germanroughhairedpointer",
        "germanshepherddog",
        "germanshorthairedpointer",
        "germanspaniel",
        "germanspitz",
        "germanwirehairedpointer",
        "giantschnauzer",
        "glenofimaalterrier",
        "goldenretriever",
        "gordonsetter",
        "greatdane",
        "greaterswissmountaindog",
        "greekharehound",
        "greenlanddog",
        "greyhound",
        "griffonbleudegascogne",
        "griffonbruxellois",
        "griffonfauvedebretagne",
        "griffonnivernais",
        "groenendaeldog",
        "gullterrier",
        "hamiltonstovare",
        "hanoverhound",
        "harrier",
        "havanese",
        "hokkaidodog",
        "hortayaborzaya",
        "hovawart",
        "huntaway",
        "hygenhound",
        "ibizanhound",
        "icelandicsheepdog",
        "indianpariahdog",
        "indianspitz",
        "irishredandwhitesetter",
        "irishsetter",
        "irishterrier",
        "irishwaterspaniel",
        "irishwolfhound",
        "istrianhound",
        "italiangreyhound",
        "jackrussellterrier",
        "jagdterrier",
        "jamthund",
        "japanesechin",
        "japanesespitz",
        "japaneseterrier",
        "kaiken",
        "kangaldog",
        "karakachandog",
        "karelianbeardog",
        "karstshepherd",
        "keeshond",
        "kerrybeagle",
        "kerryblueterrier",
        "kingcharlesspaniel",
        "kintamani",
        "kishuken",
        "kokoni",
        "komondor",
        "kooikerhondje",
        "koolie",
        "koreanjindodog",
        "kromfohrlander",
        "kuvasz",
        "kyileo",
        "labradorhusky",
        "labradorretriever",
        "laekenoisdog",
        "lagottoromagnolo",
        "lakelandterrier",
        "lancashireheeler",
        "landseer",
        "lapponianherder",
        "leonberger",
        "lhasaapso",
        "lithuanianhound",
        "longhairedwhippet",
        "lowchen",
        "magyaragar",
        "majorcashepherddog",
        "malinois",
        "maltese",
        "manchesterterrier",
        "maremmasheepdog",
        "mcnab",
        "mexicanhairlessdog",
        "miniatureamericanshepherd",
        "miniaturepinscher",
        "mioritic",
        "molossus",
        "montenegrinmountainhound",
        "moscowwatchdog",
        "mountaincur",
        "mudholhound",
        "mudi",
        "munsterlander",
        "neapolitanmastiff",
        "newfoundlanddog",
        "newzealandheadingdog",
        "norfolkterrier",
        "norrbottenspets",
        "northerninuitdog",
        "norwegianbuhund",
        "norwegianelkhound",
        "norwegianlundehund",
        "norwichterrier",
        "novascotiaducktollingretriever",
        "olddanishpointer",
        "oldeenglishbulldogge",
        "oldenglishsheepdog",
        "otterhound",
        "pachonnavarro",
        "papillon",
        "parsonrussellterrier",
        "pastorgarafiano",
        "patterdaleterrier",
        "pekingese",
        "pembrokewelshcorgi",
        "perrodepresacanario",
        "peruvianhairlessdog",
        "phalene",
        "pharaohhound",
        "phuquocridgeback",
        "picardyspaniel",
        "plotthound",
        "podencocanario",
        "poitevin",
        "polishgreyhound",
        "polishhound",
        "polishhuntingdog",
        "polishlowlandsheepdog",
        "polishtatrasheepdog",
        "pomeranian",
        "poodle",
        "porcelaine",
        "portuguesepodengo",
        "portuguesepointer",
        "portuguesesheepdog",
        "portuguesewaterdog",
        "posavachound",
        "pragueratter",
        "pudelpointer",
        "pug",
        "puli",
        "pumi",
        "pungsandog",
        "pyreneanmastiff",
        "pyreneanmountaindog",
        "pyreneanshepherd",
        "rafeirodoalentejo",
        "rajapalayamdog",
        "rampurgreyhound",
        "rastreadorbrasileiro",
        "ratonerobodegueroandaluz",
        "ratonerovalenciano",
        "ratterrier",
        "redbonecoonhound",
        "rhodesianridgeback",
        "rottweiler",
        "roughcollie",
        "russellterrier",
        "russianspaniel",
        "russiantoy",
        "russoeuropeanlaika",
        "saarlooswolfdog",
        "sabuesoespanol",
        "saintusugespaniel",
        "saluki",
        "samoyed",
        "sapsali",
        "sarplaninac",
        "schapendoes",
        "schillerhound",
        "schipperke",
        "schweizerlaufhund",
        "scottishdeerhound",
        "scottishterrier",
        "sealyhamterrier",
        "segugioitaliano",
        "serbianhound",
        "sharpei",
        "shetlandsheepdog",
        "shibainu",
        "shihtzu",
        "shikoku",
        "siberianhusky",
        "siciliangreyhound",
        "silkenwindhound",
        "skyeterrier",
        "sloughi",
        "slovakcuvac",
        "slovakianroughhairedpointer",
        "slovenskykopov",
        "smalandsstovare",
        "smoothcollie",
        "smoothfoxterrier",
        "softcoatedwheatenterrier",
        "southrussianovcharka",
        "spanishmastiff",
        "spanishwaterdog",
        "spinoneitaliano",
        "sportinglucasterrier",
        "stabyhoun",
        "staffordshirebullterrier",
        "standardschnauzer",
        "stbernard",
        "sussexspaniel",
        "swedishlapphund",
        "swedishvallhund",
        "taigan",
        "tandog",
        "teddyrooseveltterrier",
        "telomian",
        "tennesseetreeingbrindle",
        "tenterfieldterrier",
        "tervurendog",
        "thaibangkaewdog",
        "thairidgeback",
        "tibetanmastiff",
        "tibetanspaniel",
        "tibetanterrier",
        "tornjak",
        "tosa",
        "toyfoxterrier",
        "transylvanianhound",
        "treeingcur",
        "treeingwalkercoonhound",
        "tyroleanhound",
        "uruguayancimarron",
        "villanodelasencartaciones",
        "vizsla",
        "volpinoitaliano",
        "weimaraner",
        "welshsheepdog",
        "welshspringerspaniel",
        "welshterrier",
        "westhighlandwhiteterrier",
        "westsiberianlaika",
        "wetterhoun",
        "whippet",
        "whiteshepherd",
        "whiteswissshepherddog",
        "wirefoxterrier",
        "wirehairedpointinggriffon",
        "wirehairedvizsla",
        "yorkshireterrier",
    ]}
}

